framework:
  rate_limiter:
    auth:
      policy: fixed_window
      limit: 10
      interval: '15 minutes'
    contact:
      policy: fixed_window
      limit: 10
      interval: '1 hour'
    payments:
      policy: sliding_window
      limit: 20
      interval: '15 minutes'

